In [9]:
%matplotlib inline
import numpy as np
import random
from matplotlib import pyplot as plt
import math

def sigmoid(uVal):
    return (1/(1+(np.exp(-uVal))))

def sigmoid_prime(uVal):
    return uVal*(1-uVal)

features=3
lr=0.06
errorList=[]

x1=list(np.random.uniform(-0.5,0.5,50))
y1=list(np.random.uniform(-0.5,0.5,50))
x3=np.ones(100)

t=list(np.zeros(50))

deg=np.random.uniform(0,360,50)
r=np.random.uniform(3,4,50)

for i in range(0,len(deg)):
    degInRad=(deg[i]*math.pi)/180
    
    r_ran=np.random.choice(r)
    x=r_ran*math.cos(degInRad)
    y=r_ran*math.sin(degInRad)
     
    x1.append(x)
    y1.append(y)
    t.append(1)
t=np.array(t).reshape(100,1)

x=np.array(list(zip(x1,y1,x3)))

def network(features,in_nodes,hid_nodes,out_nodes):
    w1=np.random.uniform(-2.0,2,[features,in_nodes])
    w2=np.random.uniform(-2.0,2,[in_nodes,hid_nodes])
    
    w3=np.random.uniform(-2.0,2,[hid_nodes,out_nodes])

    b1=np.random.uniform(-2.0,2,in_nodes)
    b2=np.random.uniform(-2.0,2,hid_nodes)
    b3=np.random.uniform(-2.0,2,out_nodes)
    
    dw1=np.zeros([features,in_nodes])
    dw2=np.zeros([in_nodes,hid_nodes])
    dw3=np.zeros([hid_nodes,out_nodes])

    db1=np.zeros(in_nodes)
    db2=np.zeros(hid_nodes)
    db3=np.zeros(out_nodes)
    
    
    
    while True:
        totalError=0
        
        for i in range(len(t)):
            u1=np.dot(x[i],w1)+b1
            u1Act=sigmoid(u1)
            
            u2=np.dot(u1Act,w2)+b2
            u2Act=sigmoid(u2)
           

            u3=np.dot(u2Act,w3)+b3
            y=sigmoid(u3)

            error=((y-t[i])**2)
            totalError+=error
            der_error=(y-t[i])

            errorList.append(error)
            
            dw3=np.transpose([(lr*der_error*sigmoid_prime(y))*u2Act])
            print(np.shape(dw3))
            db3=lr*der_error*sigmoid_prime(y)

            w3=w3-dw3
            b3=b3-db3

            sum=np.sum(der_error*sigmoid_prime(y))
            dw2=np.transpose([lr*der_error*sum*sigmoid_prime(u2Act)*hidden for hidden in u1Act])
            db2=lr*der_error*sum*sigmoid_prime(u2Act)
            
            
            w2=w2.T-dw2
            b2=b2-db2
            
            sum_input=np.sum(sum*sigmoid_prime(u2Act))
            dw1=np.transpose([lr*der_error*sum_input*sigmoid_prime(u1Act)*input for input in x[i]])
            db1=lr*der_error*sum_input*sigmoid_prime(u1Act)
            
            w1=w1.T-dw1
            b1=b1-db1
            
            if(totalError<0.01):
                print('solution',totalError)
                break;
            
            
            

network(3,3,4,1)       
fig = plt.figure()    
ax = plt.axes(projection='3d')   
for i in range(len(x1)):
    if(t[i]==0):

        ax.scatter(x1[i],y1[i],x3[i],color='red')
    else:
        ax.scatter(x1[i],y1[i],x3[i],color='green')


# x=np.linspace(-3,3,num=10)
# y=np.linspace(-3,3,num=10)
# x,y=np.meshgrid(x,y)

# z=(-w1*x-w2*y-w4)/w3

# display.display(plt.gcf()) 
# ax.plot_surface(x,y,z,alpha=0.5,color='red')

# display.clear_output(wait=True)

# time.sleep(0.001)


# plt.show()


(4, 1)


ValueError: shapes (3,) and (4,3) not aligned: 3 (dim 0) != 4 (dim 0)

In [7]:
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)
print(x1)
print(x2)
x1 * x2

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[0. 1. 2.]


array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])

In [15]:
w3=np.array([[1],[2],[3],[4]])
dw3=[1,2,3,4]
w3-np.array(dw3)

array([[ 0, -1, -2, -3],
       [ 1,  0, -1, -2],
       [ 2,  1,  0, -1],
       [ 3,  2,  1,  0]])